library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
use IEEE.NUMERIC_STD.ALL;
use work.pkg_neural_types.ALL;

entity Input_Processing_Block is
    Port ( 
        clk                : in  std_logic;
        rst                : in  std_logic;
        
        -- Inputs from ADC/System
        i_in               : in  data_t;
        q_in               : in  data_t;
        input_valid        : in  std_logic;
        
        -- Outputs to Neural Net
        envelope_out       : out data_t;
        theta_unwrapped_out: out data_t; -- For final recombination
        theta_norm_out     : out data_t; -- For LUTs (diff)
        buffers_enable     : out std_logic -- Delayed valid signal
    );
end Input_Processing_Block;

architecture Behavioral of Input_Processing_Block is

    -- Component CORDIC (Assumed to be generated by ISE)
    component cordic_rect_to_polar
    port (
        clk : in std_logic;
        x_in : in std_logic_vector(31 downto 0);
        y_in : in std_logic_vector(31 downto 0);
        x_out : out std_logic_vector(31 downto 0);
        phase_out : out std_logic_vector(31 downto 0)
    );
    end component;

    -- Constants
    constant PI_FIXED : data_t := to_signed(205887, 32); -- 3.14159 * 2^16
    constant TWO_PI   : data_t := to_signed(411774, 32);
    
    -- [ATENÇÃO] Mantenha este valor em 40 se foi o que funcionou para você!
    constant CORDIC_LATENCY : integer := 40; 

    -- Internal Signals
    signal cordic_x_slv, cordic_y_slv : std_logic_vector(31 downto 0);
    signal cordic_mag_slv, cordic_pha_slv : std_logic_vector(31 downto 0);
    
    signal envelope_s, phase_raw : data_t;
    signal phase_high_res : signed(31 downto 0); -- Fase crua do CORDIC (alta resolução)
    
    -- Delay Line
    signal valid_sr : std_logic_vector(CORDIC_LATENCY downto 0) := (others => '0');
    signal buffers_enable_int : std_logic := '0';

    -- Phase Logic
    signal last_phase_wrapped : data_t := (others => '0');
    signal last_phase_unwrapped : data_t := (others => '0');
    signal theta_unwrapped_reg : data_t := (others => '0');
    signal theta_norm_reg : data_t := (others => '0');

begin

    -- 1. CORDIC Instantiation
    cordic_x_slv <= std_logic_vector(i_in);
    cordic_y_slv <= std_logic_vector(q_in);

    CORDIC_INST : cordic_rect_to_polar
    port map (
        clk => clk,
        x_in => cordic_x_slv,
        y_in => cordic_y_slv,
        x_out => cordic_mag_slv,
        phase_out => cordic_pha_slv
    );

    envelope_s <= signed(cordic_mag_slv);
    
    -- [CORREÇÃO] Ajuste de Escala da Fase (Q3.29 -> Q16.16)
    -- O CORDIC entrega fase com muito mais bits fracionários.
    -- Precisamos descartar os 13 bits menos significativos para casar com Q16.16.
    phase_high_res <= signed(cordic_pha_slv);
    
    -- Shift Right Aritmético de 13 bits (divide por 8192)
    -- Usamos resize para manter 32 bits
    phase_raw <= resize(shift_right(phase_high_res, 13), 32);

    -- 2. Delay Line for Input Valid (Sync with CORDIC output)
    process(clk)
    begin
        if rising_edge(clk) then
            if rst = '1' then
                valid_sr <= (others => '0');
            else
                -- Shift Register: [N-1..0] & new_bit
                valid_sr <= valid_sr(CORDIC_LATENCY-1 downto 0) & input_valid;
            end if;
        end if;
    end process;
    
    -- The output of the delay line enables the downstream logic
    buffers_enable_int <= valid_sr(CORDIC_LATENCY);
    buffers_enable     <= buffers_enable_int;

    -- 3. Phase Logic (Unwrap and Difference)
    -- This runs exactly when data emerges from CORDIC (buffers_enable_int = '1')
    process(clk)
        variable diff : data_t;
    begin
        if rising_edge(clk) then
            if rst = '1' then
                last_phase_wrapped <= (others => '0');
                last_phase_unwrapped <= (others => '0');
                theta_unwrapped_reg <= (others => '0');
                theta_norm_reg <= (others => '0');
                envelope_out <= (others => '0');
            elsif buffers_enable_int = '1' then
                -- Calculate difference
                diff := phase_raw - last_phase_wrapped;
                
                -- Wrap Logic (-pi to +pi)
                if diff > PI_FIXED then
                    diff := diff - TWO_PI;
                elsif diff < -PI_FIXED then
                    diff := diff + TWO_PI;
                end if;
                
                -- Accumulate Unwrapped Phase
                theta_unwrapped_reg <= last_phase_unwrapped + diff;
                
                -- Update History
                last_phase_wrapped <= phase_raw;
                last_phase_unwrapped <= last_phase_unwrapped + diff;
                
                -- Outputs
                theta_norm_out <= diff;      -- Used for Conv Input (Delta Phase)
                envelope_out   <= envelope_s; -- Envelope passes through
            end if;
        end if;
    end process;
    
    theta_unwrapped_out <= theta_unwrapped_reg;

end Behavioral;